# The NumPy ndarray: A Multidimensional Array Object（ndarray: 多维数组对象）

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[  4.58506162e-01,  -1.70890163e-03,   1.95819931e+00],
       [  2.46371288e-01,   7.71997724e-01,   1.21269171e+00]])

In [3]:
data * 10

array([[  4.58506162e+00,  -1.70890163e-02,   1.95819931e+01],
       [  2.46371288e+00,   7.71997724e+00,   1.21269171e+01]])

In [4]:
data + data

array([[  9.17012324e-01,  -3.41780326e-03,   3.91639863e+00],
       [  4.92742575e-01,   1.54399545e+00,   2.42538341e+00]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

## 1 Greating ndarrays (创建n维数组)

In [7]:
data1 = [6, 7.5, 8, 9, 5, 10]
arr1 = np.array(data1)
arr1

array([  6. ,   7.5,   8. ,   9. ,   5. ,  10. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((5,8))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])