# The NumPy ndarray: A Multidimensional Array Object（ndarray: 多维数组对象）

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[-0.3721824 , -0.54367106, -0.16202969],
       [ 0.54419222, -0.15226644, -0.4320678 ]])

In [3]:
data * 10

array([[-3.72182402, -5.4367106 , -1.62029688],
       [ 5.44192222, -1.52266437, -4.32067798]])

In [4]:
data + data

array([[-0.7443648 , -1.08734212, -0.32405938],
       [ 1.08838444, -0.30453287, -0.8641356 ]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

## 1 Greating ndarrays (创建n维数组)

In [7]:
data1 = [6, 7.5, 8, 9, 5, 10]
arr1 = np.array(data1)
arr1

array([  6. ,   7.5,   8. ,   9. ,   5. ,  10. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((5,8))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2 Data Types for ndarrays

In [14]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype

dtype('float64')

In [15]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [16]:
# 还可以用astype把string里的数字变为实际的数字
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'],
      dtype='|S4')

In [17]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

要十分注意numpy.string_类型，这种类型的长度是固定的，所以可能会直接截取部分输入而不给警告。

如果转换（casting）失败的话，会给出一个ValueError提示。

In [18]:
# 还可以利用类型的缩写，比如u4就代表unit32
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([         0,          0,  274295521, 2684354560,   32768002,
                1,   32660144,     131073], dtype=uint32)

## 3 Arithmetic with NumPy Arrays（数组计算）

数组之所以重要，是因为不用写for循环就能表达很多操作，这种特性叫做vectorization(向量化)。任何两个大小相等的数组之间的运算，都是element-wise（点对点）

In [19]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [20]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [21]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [23]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [24]:
arr ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [25]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [26]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

## 4 Basic Indexing and Slicing（基本的索引和切片）

In [27]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5:8]

array([5, 6, 7])

In [29]:
arr[5:8] = 12

In [30]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])


这里把12赋给arr[5:8]，其实用到了broadcasted（我觉得应该翻译为广式转变）。这里有一个比较重要的概念需要区分，python内建的list与numpy的array有个明显的区别，这里array的切片后的结果只是一个views（视图），用来代表原有array对应的元素，而不是创建了一个新的array。但list里的切片是产生了一个新的list

In [31]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [32]:
arr_slice[1] = 12345

In [33]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [34]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

之所以这样设计是出于性能和内存的考虑，毕竟如果总是复制数据的话，会很影响运算时间。当然如果想要复制，可以使用copy()方法，比如arr[5:8].copy()

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

有两种方式可以访问单一元素

In [36]:
arr2d[0][2]

3

In [37]:
arr2d[0, 2]

3

In [38]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
old_values = arr3d[0].copy()

arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[1, 0]

array([7, 8, 9])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2, 1:] # 前两行，第二列之后

array([[2, 3],
       [5, 6]])

In [45]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [46]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 5 Boolean Indexing (布尔索引)

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [48]:
data = np.random.randn(7, 4)
data

array([[-0.88288862,  0.1259143 , -0.38641936,  1.44376038],
       [-0.4242486 , -0.85115198, -0.81995568, -0.36778073],
       [-0.86231037, -0.15299497,  0.22853492,  0.30037053],
       [ 0.45818947, -1.63160938, -2.25985432,  0.15836652],
       [ 0.29933658,  0.66705257, -0.29623002,  0.8297285 ],
       [ 0.02663935, -1.58903231,  1.49019066, -0.4413062 ],
       [-0.52388788,  1.0108966 , -1.23798819,  1.22038697]])

假设每一个name对应data数组中的一行，我们想要选中name为'Bob'的所有行。就像四则运算，用比较运算符（==）

In [49]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [50]:
data[names == 'Bob']

array([[-0.88288862,  0.1259143 , -0.38641936,  1.44376038],
       [ 0.45818947, -1.63160938, -2.25985432,  0.15836652]])

注意：布尔数组和data数组的长度要一样。

我们可以选中names=='Bob'的行，然后索引列

In [51]:
data[names == 'Bob', 2:]

array([[-0.38641936,  1.44376038],
       [-2.25985432,  0.15836652]])

In [52]:
data[names == 'Bob', 3]

array([ 1.44376038,  0.15836652])

选中除了'Bob'外的所有行，可以用!=或者~

In [56]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [57]:
data[~(names == 'Bob')]

array([[-0.4242486 , -0.85115198, -0.81995568, -0.36778073],
       [-0.86231037, -0.15299497,  0.22853492,  0.30037053],
       [ 0.29933658,  0.66705257, -0.29623002,  0.8297285 ],
       [ 0.02663935, -1.58903231,  1.49019066, -0.4413062 ],
       [-0.52388788,  1.0108966 , -1.23798819,  1.22038697]])

In [58]:
cond = names == 'Bob'
data[~cond]

array([[-0.4242486 , -0.85115198, -0.81995568, -0.36778073],
       [-0.86231037, -0.15299497,  0.22853492,  0.30037053],
       [ 0.29933658,  0.66705257, -0.29623002,  0.8297285 ],
       [ 0.02663935, -1.58903231,  1.49019066, -0.4413062 ],
       [-0.52388788,  1.0108966 , -1.23798819,  1.22038697]])

In [59]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [60]:
data[mask]

array([[-0.88288862,  0.1259143 , -0.38641936,  1.44376038],
       [-0.86231037, -0.15299497,  0.22853492,  0.30037053],
       [ 0.45818947, -1.63160938, -2.25985432,  0.15836652],
       [ 0.29933658,  0.66705257, -0.29623002,  0.8297285 ]])

用布尔索引总是会返回一份新创建的数据，原本的数据不会被改变。

更改值的方式也很直觉。比如我们想让所有负数变为0

In [61]:
data[data < 0] = 0
data

array([[ 0.        ,  0.1259143 ,  0.        ,  1.44376038],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.22853492,  0.30037053],
       [ 0.45818947,  0.        ,  0.        ,  0.15836652],
       [ 0.29933658,  0.66705257,  0.        ,  0.8297285 ],
       [ 0.02663935,  0.        ,  1.49019066,  0.        ],
       [ 0.        ,  1.0108966 ,  0.        ,  1.22038697]])

In [63]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.02663935,  0.        ,  1.49019066,  0.        ],
       [ 0.        ,  1.0108966 ,  0.        ,  1.22038697]])

## 6 Fancy Indexing(花式索引)

In [70]:
arr = np.zeros((8, 4))
arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [71]:
for i in range(8):
    arr[i] = i

In [72]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

想要按一定顺序选出几行，可以用一个整数list或整数ndarray来指定顺序

In [73]:
arr[[0,6,1,7]]

array([[ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.],
       [ 1.,  1.,  1.,  1.],
       [ 7.,  7.,  7.,  7.]])

In [74]:
arr[[-1,-7,-2,-8]]

array([[ 7.,  7.,  7.,  7.],
       [ 1.,  1.,  1.,  1.],
       [ 6.,  6.,  6.,  6.],
       [ 0.,  0.,  0.,  0.]])

In [75]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [76]:
arr[[1, 5, 6, 2], [0, 3, 1, 2]]

array([ 4, 23, 25, 10])

可以看到[ 4, 23, 29, 10]分别对应(1, 0), (5, 3), (7, 1), (2, 2)。不论数组有多少维，fancy indexing的结果总是一维。

对于长方形区域，有下面的方法来截取

In [77]:
arr[[1, 5, 6, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [24, 27, 25, 26],
       [ 8, 11,  9, 10]])

要记住，fancy indexing和切片不同，得到的是一个新的array。

## 7 Transposing Arrays and Swapping Axes（数组转置和轴交换）

转置也是返回一个view，而不是新建一个数组。有两种方式，一个是transpose方法，一个是T属性

In [78]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

做矩阵计算的时候，这个功能很常用，计算矩阵乘法的时候，用np.dot

In [80]:
arr = np.arange(8).reshape((4, 2))
print(arr.T)
print(arr)

[[0 2 4 6]
 [1 3 5 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [81]:
np.dot(arr.T, arr)

array([[56, 68],
       [68, 84]])

上面的例子是 (2x4) x (4x2) = (2x2)。得到的结果是2x2维，就是普通的矩阵乘法。

对于多维数组，transpose会接受由轴数字组成的tuple，来交换轴

In [82]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [83]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

这里，second axis(1)被设为第一个，first axis(0)第二个，最后的axis没变。

使用.T来转置swapping axes(交换轴)的一个特殊情况，ndarray有方法叫做swapaxes，这个方法取两个axis值，并交换这两个轴

In [84]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

swapaxes也是返回view，不生成新的data。